### ISSUE TITLE
Question about OOD detection

### ISSUE THREAD

**Issue by wasserth** [MECLabTUDA/Lifelong-nnUNet#1]
Hi,
thank you for this nice extension for nnU-Net. I want to run the OOD detection for my tasks. To make it work on my computer I had to change the following parts of the code:

Line 181 in`per_subject_evaluate.py` to 
```
patch_size = [112, 112, 192]   # this is for my task
uncertainty = mahalanobis_uncertainty(features_path, base_name, feature_key, patch_size=patch_size, norm=norm)
```

Line 181 in`per_subject_evaluate.py` to 
```
def evaluate_subject(prediction_path, target_path, label=1, merge_labels=None):
```

Line 63 in `model_restore.py` to 
```
search_in = join(list(nnunet_ext.__path__)[0], "nnunet", "training", "network_training")
```
Then I was able to run the code. However, the (mahalanobis) uncertainties I am receiving are quite different from what I would expect. A dataset with a slightly different modality from the training data received a higher uncertainty than a dataset with the same modality.
So I was wondering if I am using it correctly. I do the following (my model is a 3d_fullres model):
```
dataset = "modality_arteriell"
task = "119"
fold = "0"

feature_paths = ['conv_blocks_context.4.blocks.1.conv']

nnUNet_extract_features(str(Path(os.environ["nnUNet_raw_data_base"]) / "nnUNet_raw_data" /
                            get_full_task_name(int(task)) / "imagesTr"),
                        "training_data", feature_paths, task)

nnUNet_extract_outputs(data_dir, dataset, task_id)
nnUNet_extract_non_softmaxed_outputs(data_dir, dataset, task_id)

for idx in [10,20,30,40,50]:
    nnUNet_extract_MCDO_outputs(data_dir, dataset, idx, task_id)

nnUNet_extract_features(data_dir, dataset, feature_paths, task_id)
nnUNet_estimate_gaussian(task_id, fold, ["training_data"], [dataset], feature_paths)

nnUNet_extract_uncertainties(dataset, task_id, fold, feature_paths,
                                                label_dir, label=2, nr_labels=3, temperatures=[10, 100])
```
My task has 3 classes: 0->background, 1->class A, 2-> class B. I want to get the uncertainty for class B.

**Comment by MECLabTUDA** [comment]
Hi wasserth,
thank you for trying out our method and clarifying which changes were necessary in your case. These look good, I will later modify the code so that the 'patch_size' argument can be set earlier on.
Some small comments regarding the later part of your code:
- Is your 'task' that you set as task = '119' the same as the 'task_id' you use as an argument?
- Please note that when you set 'label=1' on 'evaluate_subject', you are calculating the metrics for your label 1 (in your case I assume class A instead of class B).
- Just to clarify, the 'mcdo_ix' arguemnt for 'nnUNet_extract_MCDO_outputs' is the index for a specific output. In this case you are extracting 5 outputs with indexes [10,20,30,40,50] and calculating the divergence between these.

I did not find any obvious error with your code. As some basic sanity checks:
- how are the uncertainties (distances) for the training data? I would suggest calculating these by adding the "training_data" dataset to the 'store_ds_names' argument of 'nnUNet_estimate_gaussian'. Intuitively, these should be considerably lower than the uncertainties for in-distribution unseen data.
- What ranges do the uncertainties occupy?

**Comment by wasserth** [comment]
Thank you for the tips. I found the problem: For the training gaussian fit (train_ds_names) I used the entire dataset. This then resulted in the validation data having very low uncertainties. By only using the training data for train_ds_name the uncertainties for the validation data are more reasonable. Now uncertainties for the training data is really low (roughly 3000), for the validation data it is medium (roughly 3.000.000) and for perturbated data it is clearly higher (roughly 10.000.000).
